### ISSUE TITLE
error: "argument of type 'PosixPath' is not iterable"

### ISSUE THREAD

**Issue by JLimperg** [leanprover-community/mathlib-tools#28]
Hey! I'm getting the error in the title whenever I try to run a `leanproject` command. For instance:

```
$ leanproject new test
> mkdir -p test
> cd test
> mkdir src
> git init -q
> git checkout -b lean-3.4.2
Switched to a new branch 'lean-3.4.2'
configuring test 0.1
argument of type 'PosixPath' is not iterable
```

```
$ leanproject get mathlib
Cloning from git@github.com:leanprover-community/mathlib.git
argument of type 'PosixPath' is not iterable
```

This is with mathlibtools-0.0.3 installed via pip (python3.6). I don't know what might be causing this, but I'll be happy to provide any additional info you might need for debugging.

**Comment by PatrickMassot** [comment]
@JLimperg Could you please try to use the branch https://github.com/leanprover-community/mathlib-tools/pull/30? It means you need to 
* `git clone https://github.com/leanprover-community/mathlib-tools.git`
* `cd mathlib-tools`
* `git checkout error-handling`
* `pip install .`  (maybe `pip3 install .`, or `sudo pip3 install .` depending on your python setup)

Then you'll be able to run `leanproject --debug get mathlib`, `leanproject --debug new test` etc. and report the output here.

**Comment by JLimperg** [comment]
Thank you for looking into this! Here's the result for `leanproject --debug build` in a `mathlib` repo:

```
Traceback (most recent call last):
  File "/home/jannis/.local/bin/leanproject", line 11, in <module>
    load_entry_point('mathlibtools==0.0.3', 'console_scripts', 'leanproject')()
  File "/home/jannis/.local/lib64/python3.6/site-packages/mathlibtools/leanproject.py", line 248, in safe_cli
    handle_exception(err, str(err))
  File "/home/jannis/.local/lib64/python3.6/site-packages/mathlibtools/leanproject.py", line 51, in handle_exception
    raise exc
  File "/home/jannis/.local/lib64/python3.6/site-packages/mathlibtools/leanproject.py", line 246, in safe_cli
    cli()
  File "/home/jannis/.local/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jannis/.local/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jannis/.local/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jannis/.local/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jannis/.local/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jannis/.local/lib64/python3.6/site-packages/mathlibtools/leanproject.py", line 102, in build
    proj().build()
  File "/home/jannis/.local/lib64/python3.6/site-packages/mathlibtools/leanproject.py", line 40, in proj
    lean_upgrade)
  File "/home/jannis/.local/lib64/python3.6/site-packages/mathlibtools/lib.py", line 233, in from_path
    repo = Repo(path, search_parent_directories=True)
  File "/home/jannis/.local/lib64/python3.6/site-packages/git/repo/base.py", line 119, in __init__
    if expand_vars and ("%" in epath or "$" in epath):
TypeError: argument of type 'PosixPath' is not iterable
```

**Comment by PatrickMassot** [comment]
Wow, that's unexpected! I'm glad I created this `--debug` option instead of trying to guess. So, it seems you have an ancient GitPython, from before https://github.com/gitpython-developers/GitPython/commit/7f08b7730438bde34ae55bc3793fa524047bb804. So the temporary fix is to `pip install --upgrade GitPython`. But of course the proper fix is on me, I need to specify a lower bound for the GitPython version.

**Comment by JLimperg** [comment]
I can confirm that upgrading GitPython (from 2.1.10 to 3.1.0) fixed the issue. Thanks again!

**Comment by PatrickMassot** [comment]
Thanks for confirming.
