### ISSUE TITLE
paramiko causing problems when running leanproject

### ISSUE THREAD

**Issue by mateoatr** [leanprover-community/mathlib-tools#41]
After installing `mathlibtools` through pip3, I'm getting this when I run `leanproject`:
```
Traceback (most recent call last):
  File "c:\users\mateo\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\mateo\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mateo\AppData\Local\Programs\Python\Python38\Scripts\leanproject.exe\__main__.py", line 4, in <module>
  File "c:\users\mateo\appdata\local\programs\python\python38\lib\site-packages\mathlibtools\leanproject.py", line 9, in <module>
    import paramiko # type: ignore
  File "c:\users\mateo\appdata\local\programs\python\python38\lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "c:\users\mateo\appdata\local\programs\python\python38\lib\site-packages\paramiko\transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "c:\users\mateo\appdata\local\programs\python\python38\lib\site-packages\paramiko\dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "c:\users\mateo\appdata\local\programs\python\python38\lib\site-packages\paramiko\pkey.py", line 31, in <module>
    import bcrypt
  File "c:\users\mateo\appdata\local\programs\python\python38\lib\site-packages\bcrypt\__init__.py", line 25, in <module>
    from . import _bcrypt
ImportError: cannot import name '_bcrypt' from partially initialized module 'bcrypt' (most likely due to a circular import) (c:\users\mateo\appdata\local\programs\python\python38\lib\site-packages\bcrypt\__init__.py)
```

I tried emptying my pip3 packages and reinstalling:
```
pip3 freeze --local | xargs pip3 uninstall -y
pip3 --no-cache-dir install mathlibtools
```
But had no luck. To get around this issue I simply commented out the `paramiko` imports in leanproject.py. I'm using pip 20.0.2 with python 3.8.0.

**Comment by PatrickMassot** [comment]
There is not much we can do in a broken python environment, but in this specific case we can try to gracefully give up ssh. Could you please try with master? It means cloning this repository and doing a `pip3 install path_to_cloned_repo`.

**Comment by mateoatr** [comment]
I tried with master but now I ran into another issue where `subprocess` is not able to find the passed command. I just put a PR for this #43.

**Comment by PatrickMassot** [comment]
paramiko is no longer used here.
