### ISSUE TITLE
leanproject@0.0.8 has a dependency on numpy, but pip doesn't install it automatically

### ISSUE THREAD

**Issue by semorrison** [leanprover-community/mathlib-tools#52]
```
arguta:mathlib scott$ leanproject up
Traceback (most recent call last):
  File "/usr/local/bin/leanproject", line 5, in <module>
    from mathlibtools.leanproject import safe_cli
  File "/usr/local/lib/python3.7/site-packages/mathlibtools/leanproject.py", line 20, in <module>
    from mathlibtools.lib import (LeanProject, log, LeanDirtyRepo,
  File "/usr/local/lib/python3.7/site-packages/mathlibtools/lib.py", line 16, in <module>
    import networkx as nx # type: ignore
  File "/usr/local/lib/python3.7/site-packages/networkx/__init__.py", line 115, in <module>
    import networkx.readwrite
  File "/usr/local/lib/python3.7/site-packages/networkx/readwrite/__init__.py", line 15, in <module>
    from networkx.readwrite.graphml import *
  File "/usr/local/lib/python3.7/site-packages/networkx/readwrite/graphml.py", line 314, in <module>
    class GraphML(object):
  File "/usr/local/lib/python3.7/site-packages/networkx/readwrite/graphml.py", line 344, in GraphML
    types = [(np.float64, "float"), (np.float32, "float"),
AttributeError: module 'numpy' has no attribute 'float64'
arguta:mathlib scott$ pip3 install numpy
Collecting numpy
  Downloading numpy-1.18.4-cp37-cp37m-macosx_10_9_x86_64.whl (15.1 MB)
     |████████████████████████████████| 15.1 MB 3.1 MB/s 
Installing collected packages: numpy
Successfully installed numpy-1.18.4
arguta:mathlib scott$ leanproject up
```
(success!)

**Comment by gebner** [comment]
Did you have numpy installed before?  `networkx` has special code that handles the case where you don't have `numpy` installed.  (And indeed `leanproject` works here without `numpy`.)

**Comment by PatrickMassot** [comment]
Here I haven't numpy installed and leanproject is working.

**Comment by PatrickMassot** [comment]
And also no new dependency was added since 0.0.6. The 0.0.8 release was purely bug fixing.

**Comment by semorrison** [comment]
My understanding is that I didn't have it installed.

I actually "cleaned up" the copy-pasted transcript above, and perhaps I shouldn't have --- before issuing `pip3 install numpy`, I also ran `pip3 uninstall numpy`, and was told that it wasn't installed.

**Comment by PatrickMassot** [comment]
Maybe I wasn't clear. When I write "I don't have numpy", I don't mean that mathlibtools installed it: I *currently* don't have numpy and leanproject is running fine.

**Comment by PatrickMassot** [comment]
I closed since nobody else can reproduce this issue, but feel free to reopen if it becomes deterministic.
